import Link from "next/link";
import { Button } from "@/components/ui/button";
import { productGlobalAccount } from "@/lib/content";

function AccountVisual() {
  const { account } = productGlobalAccount;
  return <div className="global-account-float"><div className="relative h-[452px] w-[720px] overflow-hidden rounded-[28px] bg-white shadow-[0_60px_120px_rgba(10,25,18,.5)]"><div aria-hidden="true" className="absolute inset-0 bg-[linear-gradient(190deg,rgba(219,252,0,.18),rgba(255,255,255,0)_45%)]" /><div className="relative flex h-full flex-col p-[42px_48px] text-left text-[#0E2A1E]"><div className="flex items-start justify-between"><div><div className="text-[26px] font-extrabold tracking-tight text-brand">Kaloq<span aria-hidden="true" className="ml-1 inline-block h-2 w-2 translate-y-2.5 rounded-full bg-lime" /></div><div className="mt-1 text-[11px] font-semibold uppercase tracking-[0.16em] text-[#7A8378]">Global Account</div></div><span className="rounded-full border border-[#D7E69A] bg-[#F4F9D9] px-3 py-1.5 text-[11px] font-semibold text-[#557000]">USD Available</span></div><div className="mt-7"><div className="text-[12px] text-[#7A8378]">{account.balanceLabel}</div><div className="mt-1 font-mono text-[38px] tracking-[-0.04em]">{account.balance}</div></div><div className="mt-6 grid grid-cols-3 gap-3">{account.balances.slice(0, 3).map((balance) => <div key={balance.label} className="rounded-2xl border border-[#E8E2D1] bg-white/80 p-4"><div className="text-[11px] text-[#7A8378]">{balance.label}{balance.status !== "Available" && <span className="ml-1 text-[9px] font-semibold text-[#557000]">(Coming Soon)</span>}</div><div className="mt-2 font-mono text-[16px]">{balance.value}</div>{balance.status === "Available" && <div className="mt-1 text-[10px] font-semibold text-[#557000]">Available</div>}</div>)}</div><div className="mt-auto flex items-center justify-between rounded-2xl bg-[#0E2A1E] px-5 py-4 text-white"><div><div className="text-[12px] font-semibold">USD balance</div><div className="mt-0.5 text-[11px] text-white/55">Connected to Kaloq Card</div></div><span className="rounded-full bg-lime px-3 py-1 text-[10px] font-semibold text-[#0E2A1E]">Available</span></div></div></div></div>;
}

export function GlobalAccountHero() {
  const { hero } = productGlobalAccount;
  return <section data-hero-overlay className="relative -mt-[calc(4rem+1px)] h-[1220px] overflow-hidden bg-[#0E2A1E] text-center max-[640px]:h-[1120px]"><div aria-hidden="true" className="global-account-hero-bg absolute inset-0" /><div aria-hidden="true" className="global-account-hero-dots absolute inset-0 opacity-[.28]" /><div className="relative z-[4] px-6 pt-[150px]"><p className="text-xs font-semibold uppercase tracking-[0.14em] text-white/60">{hero.eyebrow}</p><h1 className="mx-auto mt-4 max-w-3xl font-display text-[clamp(48px,5vw,64px)] font-normal leading-[1.06] tracking-[-0.01em] text-white">{hero.h1Line1}<br />{hero.h1Line2} <em className="not-italic italic text-lime">{hero.h1Accent}</em>.</h1><p className="mx-auto mt-[22px] max-w-[600px] text-lg leading-[1.55] text-white/78">{hero.sub}</p><div className="mt-[30px] flex flex-wrap justify-center gap-3"><Button href={hero.primaryCta.href} className="bg-lime px-[30px] py-3.5 text-base font-semibold !text-[#0E2A1E] hover:bg-lime-hover">{hero.primaryCta.label}</Button><Link href={hero.secondaryCta.href} className="inline-flex items-center justify-center rounded-full border border-white/22 bg-white/12 px-[30px] py-3.5 text-base font-semibold text-white hover:bg-white/24">{hero.secondaryCta.label}</Link></div></div><div className="absolute inset-x-0 bottom-[84px] z-[4] flex justify-center px-4"><div className="origin-bottom scale-[0.46] sm:scale-[0.68] md:scale-[0.86] lg:scale-100"><AccountVisual /></div></div><div className="absolute bottom-[22px] left-1/2 z-[5] -translate-x-1/2 whitespace-nowrap rounded-full bg-white/50 px-5 py-2 text-[12.5px] text-[#3A3426] backdrop-blur-[8px]">{hero.compliance}</div></section>;
}
